# -*- coding: utf-8 -*-
"""Final_term_project_CS22A - It’s time to wake up!: Using data to understand climate change - Vihaan Khandelwal (017844372) - Snehal Bakshi (017892992))

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SJQm8rBvH6bBFJCz80YZ9Bc1lPUKfWut

# Has the global temperature changed significantly in the year 1995 compared to the year 2020?

###Let's figure out using a two sample T-Test on the dataset  


---



First we have to establish what our hypothesis are

H₀ = There is no change between the “AvgTemprature” recorded in the year 1995 and the “AvgTemprature” recorded in the year 2020   


H₁ = there is significant change between the “AvgTemprature” recorded in the year 1995 and the “AvgTemprature” recorded in the year 2020

---   

Dataset: https://raw.githubusercontent.com/csbfx/cs22a/main/global_climate.csv

Title: It's time to wake up! Using data to understand climate change

Vihaan Khandelwal (017844372)

Snehal Bakshi (017892992)

Introduction:

The first thing that we wanted to ask with the dataset was “Has the global temperature changed significantly in the year 1995 compared to the year 2020”. We picked this question as we could use a two sample T-Test to find if there was a change between the independent “Year” variable and the dependent “AvgTemprature” variable. The null hypothesis (H₀) assumes that there is no change between the “AvgTemprature” recorded in the year 1995 and the “AvgTemprature” recorded in the year 2020. On the other hand, the alternative hypothesis (H₁) says that there was a change in the temperature due to climate change caused by human activity.

The second question we are thinking about is if a country being more hot has to do with the continent’s financial wealth. We picked this question because we are curious to understand if there is a positive or negative relationship between the two variables. We plan on doing this by adding two data sets together to include financial data about the per capita gdp by continent which we currently are not given. Additionally we will focus on the year 2019, as this is the latest year without COVID 19 as a confounding variable.

Data:

We are trying to understand the global temperature trends from 1995 to 2020 using data from the GSOD database. We are aiming to investigate if there has been an increase in global temperature during this time frame. Additionally, we are using data from the International Monetary Fund as it gives us data for the GDP by thousands for the seven different regions we are analyzing.
"""

from scipy.stats import ttest_rel
import pandas as pd
data_url = 'https://raw.githubusercontent.com/csbfx/cs22a/main/global_climate.csv'

climate_df = pd.read_csv(data_url)
climate_df

from scipy.stats import ttest_rel
import pandas as pd
data_url = 'https://raw.githubusercontent.com/csbfx/cs22a/main/global_climate.csv'

climate_df = pd.read_csv(data_url)
from scipy.stats import ttest_ind

group1 = climate_df[climate_df['Year'] == 1995]['AvgTemperature']
group2 = climate_df[climate_df['Year'] == 2020]['AvgTemperature']

results_1 = ttest_ind(group1, group2)
print(f"P-Value: {results_1.pvalue}")
print(f"T-Statistic:  {round(results_1.statistic,2)}")

import pandas as pd
import matplotlib.pyplot as plt

data_url = 'https://raw.githubusercontent.com/csbfx/cs22a/main/global_climate.csv'
climate_df = pd.read_csv(data_url)

avg_temp_1995 = climate_df[climate_df['Year'] == 1995]['AvgTemperature'].mean()
avg_temp_2020 = climate_df[climate_df['Year'] == 2020]['AvgTemperature'].mean()

years = ['1995', '2020']
avg_temps = [avg_temp_1995, avg_temp_2020]

plt.bar(years, avg_temps, color=['blue', 'orange'])
plt.title('Average Temperature: 1995 vs 2020')
plt.xlabel('Year')
plt.ylabel('Average Temperature (°F)')
plt.show()

import matplotlib.pyplot as plt

baseline = 55

plt.figure(figsize=(8, 6))
plt.bar(["1995", "2020"], [avg_temp_1995, avg_temp_2020], color=['skyblue', 'salmon'])
plt.title("Average Temperature: 1995 vs 2020 (Adjusted Baseline)", fontsize=14)
plt.ylabel("Average Temperature (°F)", fontsize=12)
plt.ylim(baseline, max(avg_temp_1995, avg_temp_2020) + 5)
plt.grid(axis='y', linestyle='--', alpha=0.7)

for i, value in enumerate([avg_temp_1995, avg_temp_2020]):
    plt.text(i, value + 0.1, f"{value:.1f}°F", ha='center', fontsize=11)

plt.show()

"""Results:
P-Value: 6.74 × 10⁻⁷
The p-value represents the probability of observing the data (or something more extreme) under the assumption that the null hypothesis is true. A very small p-value (usually less than 0.05) indicates strong evidence against the null hypothesis.

Here, the p-value
6.74
×
1
0
−
7
6.74 × 10⁻⁷
is extremely small, much smaller than the alpha of
0.05. This means that there is very strong statistical evidence to reject the null hypothesis.  

Interpretation: The difference in average temperatures between 1995 and 2020 is statistically significant.  

T-Statistic: 5.02
The t-statistic measures how many standard errors the difference between the two groups' means is from zero (the null hypothesis). A higher t-statistic indicates a greater difference between the groups.

A t-statistic of 5.02 is quite large, reinforcing the conclusion that the difference in temperatures is significant.  

---


Conclusion:
The results of the T-Test suggest that the global average temperature in 2020 is significantly different from that in 1995. Given the very small p-value and the large t-statistic, you can confidently conclude that global warming has likely contributed to a meaningful change in global temperatures between these years.

This aligns with broader scientific evidence that global temperatures have been rising over recent decades due to factors such as increased greenhouse gas emissions.







"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from scipy.stats import linregress

data_url = pd.read_csv("https://raw.githubusercontent.com/csbfx/cs22a/main/global_climate.csv")

data_df = pd.DataFrame(data_url)
data_df

grouped_data = data_df.groupby(["Region", "Year"])["AvgTemperature"].mean().reset_index()

vis_df = pd.DataFrame({
'Region': ['Africa', 'Middle East', 'North America', 'South America', 'Asia', 'Europe', 'Australia'],
'GDP': [2.04, 11.47, 49.73, 8.26, 13.68, 29.38, 52.41],
'Temperature': [avg_temp_africa, avg_temp_midEast, northAmerica_df['AvgTemperature'].mean(), southAmerica_df['AvgTemperature'].mean(), asia_df['AvgTemperature'].mean(), europe_df['AvgTemperature'].mean(), australia_df['AvgTemperature'].mean()]
})

X = vis_df['Temperature'].values.reshape(-1, 1)
y = vis_df['GDP'].values
model = LinearRegression()
model.fit(X, y)
predicted_gdp = model.predict(X)

slope, intercept, r_value, _, _ = linregress(X.flatten(), y)

print("Linear Regression Equation: y = {:.2f}x + {:.2f}".format(slope, intercept))
print("Correlation Coefficient (r): {:.2f}".format(r_value))

#Calculate the avg tempereature for regions

avg_temp_africa = africa_df["AvgTemperature"].mean()
avg_temp_midEast = midEast_df["AvgTemperature"].mean()
avg_temp_northAmerica = northAmerica_df["AvgTemperature"].mean()
avg_temp_southAmerica = southAmerica_df["AvgTemperature"].mean()
avg_temp_europe = europe_df["AvgTemperature"].mean()
avg_temp_asia = asia_df["AvgTemperature"].mean()
avg_temp_australia = australia_df["AvgTemperature"].mean()

print("The mean temp for Africa is " , round(avg_temp_africa,2))
print("The mean temp for midEast is " , round(avg_temp_midEast,2))
print("The mean temp for North America is " , round(avg_temp_northAmerica,2))
print("The mean temp for South America is " , round(avg_temp_southAmerica,2))
print("The mean temp for Europe is " , round(avg_temp_europe,2))
print("The mean temp for Asia is " , round(avg_temp_asia,2))
print("The mean temp for Australia is " , round(avg_temp_australia,2))

vis_df = pd.DataFrame({
'Region': ['Africa', 'Middle East', 'North America', 'South America', 'Asia', 'Europe', 'Australia'],
'GDP': [2.04, 11.47, 49.73, 8.26, 13.68, 29.38, 52.41],
'Temperature': [avg_temp_africa, avg_temp_midEast, northAmerica_df['AvgTemperature'].mean(), southAmerica_df['AvgTemperature'].mean(), asia_df['AvgTemperature'].mean(), europe_df['AvgTemperature'].mean(), australia_df['AvgTemperature'].mean()]
})

X = vis_df['Temperature'].values.reshape(-1, 1)
y = vis_df['GDP'].values
model = LinearRegression()
model.fit(X, y)
predicted_gdp = model.predict(X)

sns.scatterplot(x='Temperature', y='GDP', data=vis_df, hue='Region')
plt.plot(X, predicted_gdp, color='red', label='Regression line')

plt.xlabel('Average Temperature (°F)')
plt.ylabel('GDP')
plt.title('GDP vs. Average Temperature by Region')
plt.legend()
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(vis_df['Region'], vis_df['Temperature'], label='Temperature')
plt.bar(vis_df['Region'], vis_df['GDP'], label='GDP per capita')
plt.xlabel('Region')
plt.ylabel('Value')
plt.title('Average Temperature and GDP per Capita by Region')
plt.legend()
plt.xticks(rotation=45)
plt.show()

print(grouped_data)
grouped_data.to_csv("regional_average_temperatures.csv", index=False)

"""Conclusions:

We are taking away that there is a strong negative correlation between GDP and temperature and that there was a change in temperature from the year 1995 and the year 2020. In the future we would like to create a dynamic model in which we could in real time obtain data and analyze it in code through our algorithm. This could help in terms of mitigating the climate change issues our world is facing. We are also looking to improve by using regional analysis by taking into account more narrowed down regions of relevant cities instead of focusing on a larger impact by looking at regions. We also would look for a more reliable year as 2020s year had one of the lowest emissions from cars as a significantly lesser amount of people were on the roads.


Results:

Linear Regression Equation: y = -1.72x + 136.44
- The number -1.72 is indicative that when temperatures rise, the GDP drops. This concept is better visualized in the scatterplot above.

Correlation Coefficient (r): -0.76

- The correlation coefficent of -0.76 is indicative of a strong negative correlations between temperature and GDP.

The mean temp for Africa is  74.5

The mean temp for midEast is  73.73

The mean temp for North America is  55.93

The mean temp for South America is  72.63

The mean temp for Europe is  51.87

The mean temp for Asia is  68.09

The mean temp for Australia is  62.45

- The mean temperatures are indicative of the regions are there to represent the average temperature of each region


"""